name: Release APK

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Release Tag (v2.x.x)'
        required: true

jobs:
  upload-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Upload APK
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.release-tag }}
          files: app/release/app-release.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
